
version: '3'

services:

  # App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-node-larave
    container_name: delivery-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ../:/var/www/delivery
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - delivery-network
       


  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: delivery-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "7000:70"
    volumes:
      - ../:/var/www/delivery
      - ./config/nginx:/etc/nginx/conf.d
        
    networks:
      - delivery-network      
      
 

  # MySQL Service
  database:
    image: mysql:8.0
    container_name: delivery-database
    restart: unless-stopped
    tty: true
    ports:
      - 3303:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: secret
      
    volumes:
      - ../../db/mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf
    
    networks:
      - delivery-network
      
  #phpmyadmin    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: delivery-phpmyadmin
    ports:
        - '7070:80'
    restart: always
    environment:
        PMA_HOST: delivery-database
    depends_on:
        - delivery-database
    
    networks:
      - delivery-network

        
        
# volumes
volumes:
  mongodb_config:
  
# Networks Configuration
networks:
  delivery-network:
    driver: bridge
 
